extends Node

## Autoload. The one thing that has to survive the title-screen -> game.tscn
## scene swap: which mode the player picked, plus the seed high scores, which by
## definition have to outlive any single run.
##
## `endless` is read once, by Game._ready() wiring it into WaveDirector; the
## title screen is the only writer. The scores are persisted to user:// so they
## are still there next launch, not just next scene — and, since v3 of the save,
## so are the keys the player has moved (see `key_bindings`).
##
## There are two scores because there are two games. The fixed campaign ends
## after WaveDirector's eight-wave table; endless never ends. A campaign total
## and an endless total are therefore not comparable in either direction, and
## sharing one number meant a single endless run permanently retired the campaign
## record — while the title screen labelled that number "Best endless run"
## whichever mode had actually set it.
##
## THE RULE OF THIS FILE: a save we cannot understand leaves the in-memory scores
## alone. Every score in this game is re-earnable by playing except the record of
## having earned it, and `record_score` only ever raises a record — so the instant
## a bad parse writes a 0 into a slot, the next mediocre run refills it and the
## real number is gone with no way back. Silence is recoverable; a zero is not.
## Everything below follows from that: whole-file validation, a version that is
## actually compared, a write that never truncates the previous save, and a
## refusal that moves a file aside rather than over it.

const SAVE_PATH := "user://highscore.save"

## Bumped when the on-disk shape changes. Version 1 is the original single line;
## version 2 is a `vN` header followed by campaign then endless; version 3 adds a
## count of rebound keys and that many `action code [code...]` lines. Actually
## parsed and compared — see `_parse_save`.
const SAVE_VERSION: int = 3

## A `count` line claiming more rebound actions than the game has verbs is not a
## file this build wrote. Bounded so a corrupt digit cannot ask the parser for a
## million lines before it decides it does not like them.
const MAX_BINDING_ROWS: int = 32

## The file this autoload persists to. A variable rather than a constant for
## exactly one reason: the unit tests need to drive this code over a scratch file
## instead of over the player's real save, which is the single thing in this
## project that cannot be regenerated by playing. The game never reassigns it.
## `.tmp` and `.bak` siblings are derived from it, so a test redirects all three
## at once.
var save_path: String = SAVE_PATH

var endless: bool = false
## True from the moment a run beats its mode's record until the title screen has
## said so. Not persisted: it is about the journey the player just took, not about
## the save file.
##
## Without it, a record set by quitting is silent. _end_run captures
## record_score's return and hands it to the post-mortem's "a new best", but the
## two pause exits call it as a bare statement and drop it -- so leaving on a
## personal best said nothing at all, and the title screen renders the same
## sentence whether the number moved a second ago or three sessions back.
var fresh_record: bool = false

var campaign_high_score: int = 0
var endless_high_score: int = 0

## The keys the player has moved, as {action_name: Array[int] of keycodes}. Only
## the rows that differ from KeyBindings.ACTIONS live here — see
## KeyBindings.overrides() for why the defaults must not be pinned into the save.
##
## It lives in this file rather than in a settings file of its own because this is
## already the thing that survives a scene swap and already owns the one write to
## user://. A second persistence mechanism would mean a second half-written-file
## story, and this file's whole header is about how expensive that was to get
## right once.
##
## Plain data, deliberately: `_load` sets it, and applying it to the InputMap is a
## separate call (`apply_key_bindings`). A `_load` that reached into the global
## InputMap would make every test that drives this parser over a scratch file a
## test that silently rebinds the whole suite's keyboard.
var key_bindings: Dictionary = {}

## What `_load` made of the save file. Exists so that "there was no save" and
## "there was a save and it was refused" are distinguishable from the outside —
## both leave the scores where they were, and only one of them is a problem.
## One of:
##   ""          `_load` has not run yet
##   "absent"    no file, first launch — the zeros are legitimate
##   "loaded"    a current-version file was read
##   "migrated"  a version-1 file was read and rewritten in the new shape
##   "recovered" `save_path` was missing and an interrupted `_save`'s temp file
##               was complete, so it was adopted
##   "refused"   a file exists and could not be trusted; the scores were left alone
var load_status: String = ""

## The file `_load` refused, if any. The next `_save` moves it aside instead of
## writing over it: a file this build cannot read may still be one that a later
## build, or a person with a text editor, can.
var _refused_path: String = ""


func _ready() -> void:
	_load()
	apply_key_bindings()


## Pushes whatever `_load` made of the save into the live InputMap. Separate from
## `_load` on purpose (see `key_bindings`), and safe on every load path: a refused
## or absent save leaves `key_bindings` empty, which is the same instruction as
## "put every verb back on the key it ships with".
func apply_key_bindings() -> void:
	var dropped: Array[String] = KeyBindings.apply_overrides(key_bindings)
	if not dropped.is_empty():
		# Not a refusal. A save naming a verb this build does not have is a save
		# from a build that did — a downgrade, not damage — and the rest of it,
		# including two high scores, is perfectly readable.
		push_warning("RunConfig: ignoring saved bindings for %s — this build has no such action." % [dropped])


## Records the player's rebindings and writes them out. The one entry point the
## settings screen uses, so "changed on screen" and "changed on disk" cannot come
## apart.
func store_key_bindings(map: Dictionary) -> void:
	key_bindings = map
	_save()


## The record for a mode. Takes the flag rather than reading `endless`, so the
## title screen can show both without having to lie about which mode is selected.
func best_for(for_endless: bool) -> int:
	return endless_high_score if for_endless else campaign_high_score


## Called once a run ends (win or lose). Only ever raises the record — a worse
## run than last time should not overwrite the number the player is proud of.
## Files against the mode that was actually played.
func record_score(seeds_earned: int) -> bool:
	if seeds_earned <= best_for(endless):
		return false
	if endless:
		endless_high_score = seeds_earned
	else:
		campaign_high_score = seeds_earned
	fresh_record = true
	_save()
	return true


## The exact bytes of a current-version save. Split out of `_save` so the writer
## has one shape rather than a run of `store_line` calls that a later field can be
## appended to in the wrong place — and so the rows are sorted, which is what makes
## a save byte-comparable between two runs that rebound the same keys in a
## different order.
static func compose_save(campaign: int, endless_best: int, bindings: Dictionary) -> String:
	var out: PackedStringArray = [
		"v%d" % SAVE_VERSION,
		str(campaign),
		str(endless_best),
		str(bindings.size()),
	]
	var names: Array = bindings.keys()
	names.sort()
	for name: Variant in names:
		var fields: PackedStringArray = [String(name)]
		for code: Variant in (bindings[name] as Array):
			fields.append(str(int(code)))
		out.append(" ".join(fields))
	return "\n".join(out) + "\n"


## Where `_save` assembles the next file before it replaces `save_path`.
func _tmp_path() -> String:
	return save_path + ".tmp"


## Where a refused file is quarantined, rather than being overwritten.
func _backup_path() -> String:
	return save_path + ".bak"


## A score field is a plain non-negative integer and nothing else.
##
## The `""` case is the whole issue: `get_line()` returns `""` past the end of a
## truncated file, `int("")` is 0 in GDScript, and 0 is a legal-looking high
## score. Every other malformed field at least looks wrong; this one looks like a
## player who never played.
static func _is_score(text: String) -> bool:
	return text.is_valid_int() and int(text) >= 0


## An action name in the save is a lowercase identifier and nothing else. This is
## a check on the file's SHAPE, not on its vocabulary: a name this build does not
## recognise is still well-formed, and is dropped by `apply_key_bindings` rather
## than being allowed to condemn the two high scores sharing the file.
static func _is_action_name(text: String) -> bool:
	if text == "":
		return false
	return text.is_valid_ascii_identifier() and text == text.to_lower()


func _parse_failed(reason: String) -> Dictionary:
	return {"ok": false, "campaign": 0, "endless": 0, "version": 0, "bindings": {}, "reason": reason}


## Validates an entire save file and only then hands back its contents.
##
## Validate-then-commit rather than parse-defensively, deliberately: a parser
## that assigns campaign before discovering that the endless line is missing has
## already done the damage this function exists to prevent. There is no
## half-understood save worth half-adopting — the fields are two independent
## records, and taking one while dropping the other is indistinguishable from
## corruption on the next launch. So nothing here touches the live scores; the
## caller commits, or does not.
##
## Returns {ok: bool, campaign: int, endless: int, version: int, reason: String}.
func _parse_save(path: String) -> Dictionary:
	var f := FileAccess.open(path, FileAccess.READ)
	if f == null:
		return _parse_failed("cannot open it (%s)" % error_string(FileAccess.get_open_error()))
	var header: String = f.get_line().strip_edges()
	if header == "":
		return _parse_failed("it is empty")

	if not header.begins_with("v"):
		# Version 1: a bare integer on one line, and nothing else. No build ever
		# wrote a literal "v1" header, so the absence of the header IS the version.
		if not _is_score(header):
			return _parse_failed("its first line %s is neither a version nor a score" % [header])
		# That legacy number is migrated into the ENDLESS slot, and the choice is
		# not arbitrary: the title screen has always presented it as "Best endless
		# run", so that is the record the player believes they hold, and endless
		# totals dwarf campaign ones (eight waves against an unbounded run) — so a
		# legacy value that did come from a campaign is merely a hard endless
		# record, whereas the reverse migration would leave an unbeatable number
		# sitting on the eight-wave mode.
		# Version 1 predates key bindings entirely, so the migration leaves every
		# verb on the key it ships with — which is where it already was.
		return {"ok": true, "campaign": 0, "endless": int(header), "version": 1, "bindings": {}, "reason": "v1"}

	var version_text: String = header.substr(1)
	if not version_text.is_valid_int():
		return _parse_failed("its version header %s is not a number" % [header])
	var version: int = int(version_text)
	if version > SAVE_VERSION:
		# The real point of reading the version at all. A later build may write
		# four lines, or the same three in another order, or the same three
		# meaning something else. Parsing it "as if it were current" is how a
		# newer build's endless record lands in the campaign slot silently. The
		# safe response to a file from the future is to decline to read it — and,
		# just as importantly, to decline to write over it, because that file is
		# not damaged, it is simply not ours. See `_load`.
		return _parse_failed("it is version %d and this build reads at most %d" % [version, SAVE_VERSION])
	if version < 2:
		return _parse_failed("version %d never had a %s header" % [version, header])

	# Version 2 onward: campaign, then endless, one per line.
	var campaign_text: String = f.get_line().strip_edges()
	var endless_text: String = f.get_line().strip_edges()
	if not _is_score(campaign_text):
		return _parse_failed("its campaign score %s is not a number" % [campaign_text])
	if not _is_score(endless_text):
		return _parse_failed("its endless score %s is not a number" % [endless_text])

	# Version 3 adds the rebound keys: a count, then that many rows. The count is
	# what makes a truncation here detectable at all — without it, a file cut
	# after the endless score is indistinguishable from a player who never opened
	# the settings screen, and the rebindings vanish with no error. Same reasoning
	# as the empty-score case above, one field along.
	var bindings: Dictionary = {}
	if version >= 3:
		var count_text: String = f.get_line().strip_edges()
		if not count_text.is_valid_int():
			return _parse_failed("its key-binding count %s is not a number" % [count_text])
		var count: int = int(count_text)
		if count < 0 or count > MAX_BINDING_ROWS:
			return _parse_failed("it claims %d rebound keys and this build has at most %d verbs"
				% [count, MAX_BINDING_ROWS])
		for i: int in count:
			var row: String = f.get_line().strip_edges()
			var fields: PackedStringArray = row.split(" ", false)
			if fields.size() < 2:
				return _parse_failed("its key-binding row %d (%s) is not an action and at least one key" % [i, row])
			var action: String = fields[0]
			if not _is_action_name(action):
				return _parse_failed("its key-binding row %d names %s, which is not an action name" % [i, action])
			if bindings.has(action):
				return _parse_failed("it binds %s twice" % [action])
			if fields.size() - 1 > KeyBindings.MAX_KEYS_PER_ACTION:
				return _parse_failed("it puts %d keys on %s" % [fields.size() - 1, action])
			var codes: Array[int] = []
			for k: int in range(1, fields.size()):
				if not fields[k].is_valid_int() or int(fields[k]) <= 0:
					return _parse_failed("its key-binding row %d has %s where a keycode belongs" % [i, fields[k]])
				codes.append(int(fields[k]))
			bindings[action] = codes

	return {
		"ok": true,
		"campaign": int(campaign_text),
		"endless": int(endless_text),
		"version": version,
		"bindings": bindings,
		"reason": "v%d" % version,
	}


## Reads the save, or refuses to.
##
## Nothing is written on the refusal path — not the fallback, not a "repaired"
## file, nothing. Overwriting the file we just failed to read is the one action
## that turns a recoverable situation into a permanent one, and it is precisely
## what the old version-1 branch did on every launch.
func _load() -> void:
	var path: String = save_path
	var recovered: bool = false
	# Whatever a previous load refused, this one supersedes: a quarantine that is
	# still pending against a file nobody is going to read again is just a stale
	# rename waiting to fire at the wrong moment.
	_refused_path = ""
	if not FileAccess.file_exists(path):
		# An interrupted `_save` can leave a complete temp file with no save
		# beside it. Adopting it is the entire reason `_save` writes it
		# separately; without this, the safety net catches nothing.
		if not FileAccess.file_exists(_tmp_path()):
			load_status = "absent"
			return
		path = _tmp_path()
		recovered = true

	var parsed: Dictionary = _parse_save(path)
	if not bool(parsed["ok"]):
		load_status = "refused"
		_refused_path = path
		push_warning("RunConfig: refusing %s because %s. High scores left as they are (campaign %d, endless %d)."
			% [path, str(parsed["reason"]), campaign_high_score, endless_high_score])
		return

	campaign_high_score = int(parsed["campaign"])
	endless_high_score = int(parsed["endless"])
	key_bindings = parsed["bindings"] as Dictionary
	if recovered:
		load_status = "recovered"
		_save()
	elif int(parsed["version"]) < SAVE_VERSION:
		load_status = "migrated"
		# Rewrite immediately in the new shape, so the ambiguity is resolved once
		# rather than being re-guessed on every launch. Unlike the refusal path,
		# this write follows a parse that fully succeeded.
		_save()
	else:
		load_status = "loaded"


## Assembles the file at a temp path and only then replaces `save_path`.
##
## Judged warranted, not ceremony, for a file this small. `FileAccess.WRITE`
## truncates its target the instant it opens, so the previous shape destroyed the
## only copy of an unregenerable number *before* writing a byte of the
## replacement — and it did that on every new record. A full or read-only user://
## therefore turned "could not save" into "the previous save is now a zero-length
## file", which is the exact truncation the reader above now has to refuse. Fixing
## only the reader would leave that: the live session keeps its number, and the
## next launch starts at zero anyway. The write side is the half that actually
## keeps the data.
##
## Honest caveat: Godot's `DirAccess.rename_absolute` removes an existing
## destination before renaming on Windows, so this is not a true atomic swap
## there. It shrinks the window from "the whole write" to "one rename", and the
## finished temp file is still on disk if we lose even that — which is why `_load`
## adopts the temp when the save has gone missing.
func _save() -> void:
	if _refused_path != "":
		# Move the file `_load` could not read aside rather than over it. First
		# refusal wins: that file is the one closest to the data the player set,
		# and a second corruption should not be allowed to bury it.
		if FileAccess.file_exists(_refused_path) and not FileAccess.file_exists(_backup_path()):
			DirAccess.rename_absolute(_refused_path, _backup_path())
		_refused_path = ""

	var tmp: String = _tmp_path()
	var f := FileAccess.open(tmp, FileAccess.WRITE)
	if f == null:
		push_warning("RunConfig: cannot write %s (%s). The record stands in memory only, and the previous save is untouched."
			% [tmp, error_string(FileAccess.get_open_error())])
		return
	f.store_string(compose_save(campaign_high_score, endless_high_score, key_bindings))
	f.flush()
	var write_error: int = f.get_error()
	f.close()
	if write_error != OK:
		# A short write is exactly the truncation this whole issue is about. Here
		# it lands in the temp file, where it can be thrown away instead of read.
		push_warning("RunConfig: %s while writing %s. Keeping the previous save."
			% [error_string(write_error), tmp])
		DirAccess.remove_absolute(tmp)
		return
	var readback: Dictionary = _parse_save(tmp)
	if not bool(readback["ok"]):
		# Read back through the same validator the loader uses, so "whatever is at
		# save_path parses" is true by construction rather than by argument — and
		# so a future writer that its own reader cannot read fails here, loudly,
		# instead of at some player's next launch.
		push_warning("RunConfig: %s does not read back (%s). Keeping the previous save."
			% [tmp, str(readback["reason"])])
		DirAccess.remove_absolute(tmp)
		return
	var rename_error: int = DirAccess.rename_absolute(tmp, save_path)
	if rename_error != OK:
		push_warning("RunConfig: %s replacing %s. The finished save is at %s and _load will adopt it."
			% [error_string(rename_error), save_path, tmp])
