extends Node

## Autoload. The one thing that has to survive the title-screen -> game.tscn
## scene swap: which mode the player picked, plus the seed high scores and the
## earned milestone flags, all of which by definition have to outlive any single
## run.
##
## `endless` is read once, by Game._ready() wiring it into WaveDirector; the
## title screen is the only writer. The scores are persisted to user:// so they
## are still there next launch, not just next scene.
##
## There are two scores because there are two games. The fixed campaign ends
## after WaveDirector's eight-wave table; endless never ends. A campaign total
## and an endless total are therefore not comparable in either direction, and
## sharing one number meant a single endless run permanently retired the campaign
## record — while the title screen labelled that number "Best endless run"
## whichever mode had actually set it.
##
## THE RULE OF THIS FILE: a save we cannot understand leaves the in-memory scores
## alone. Every score in this game is re-earnable by playing except the record of
## having earned it, and `record_score` only ever raises a record — so the instant
## a bad parse writes a 0 into a slot, the next mediocre run refills it and the
## real number is gone with no way back. Silence is recoverable; a zero is not.
## Everything below follows from that: whole-file validation, a version that is
## actually compared, a write that never truncates the previous save, and a
## refusal that moves a file aside rather than over it.

const SAVE_PATH := "user://highscore.save"

## Bumped when the on-disk shape changes. Version 1 is the original single line;
## version 2 is a `vN` header followed by campaign then endless; version 3 adds a
## fourth line holding the earned milestone ids. Actually parsed and compared now
## — see `_parse_save`.
const SAVE_VERSION: int = 3

## The milestone line's leading character, and the whole reason it has one.
##
## `get_line()` returns "" past the end of a truncated file, so a v3 save cut after
## the endless line hands the parser an empty milestone line — which is also what a
## player who has earned nothing legitimately has. Those two must not read the same,
## for exactly the reason `_is_score` spells out about `int("")`. So the empty set is
## written `m0`, a length is carried, and "" is not a valid line at all.
const MILESTONE_PREFIX := "m"
## Characters an id may contain. Ids are written by this project, never by a player,
## so the set is deliberately narrow: anything outside it is corruption, not taste.
const MILESTONE_ID_CHARS := "abcdefghijklmnopqrstuvwxyz0123456789_"

## The file this autoload persists to. A variable rather than a constant for
## exactly one reason: the unit tests need to drive this code over a scratch file
## instead of over the player's real save, which is the single thing in this
## project that cannot be regenerated by playing. The game never reassigns it.
## `.tmp` and `.bak` siblings are derived from it, so a test redirects all three
## at once.
var save_path: String = SAVE_PATH

var endless: bool = false
## True from the moment a run beats its mode's record until the title screen has
## said so. Not persisted: it is about the journey the player just took, not about
## the save file.
##
## Without it, a record set by quitting is silent. _end_run captures
## record_score's return and hands it to the post-mortem's "a new best", but the
## two pause exits call it as a bare statement and drop it -- so leaving on a
## personal best said nothing at all, and the title screen renders the same
## sentence whether the number moved a second ago or three sessions back.
var fresh_record: bool = false

var campaign_high_score: int = 0
var endless_high_score: int = 0

## Milestone ids this player has earned, as a set (`id -> true`). See
## `game/milestones.gd` for the table and the rules.
##
## A set rather than an Array because every operation this needs is a membership
## test or a union, and because the on-disk order then has to be decided once, by
## the writer, instead of drifting with whatever order a run happened to earn
## things in — a save whose bytes change when nothing changed is a save you cannot
## diff.
##
## Unlike the two scores, a lost flag is re-earnable: play another good run and it
## comes back. That asymmetry is why the milestones ride in the same file rather
## than getting a second one, and why a malformed milestone line still refuses the
## WHOLE save — the scores in it are the part that cannot be re-earned, and
## half-reading a file to rescue the cheap half is the exact move `_parse_save`
## exists to refuse.
var earned_milestones: Dictionary = {}

## What `_load` made of the save file. Exists so that "there was no save" and
## "there was a save and it was refused" are distinguishable from the outside —
## both leave the scores where they were, and only one of them is a problem.
## One of:
##   ""          `_load` has not run yet
##   "absent"    no file, first launch — the zeros are legitimate
##   "loaded"    a current-version file was read
##   "migrated"  an older-version file was read and rewritten in the new shape
##               (version 1's bare integer, or version 2's three lines with no
##               milestone line under them)
##   "recovered" `save_path` was missing and an interrupted `_save`'s temp file
##               was complete, so it was adopted
##   "refused"   a file exists and could not be trusted; the scores were left alone
var load_status: String = ""

## The file `_load` refused, if any. The next `_save` moves it aside instead of
## writing over it: a file this build cannot read may still be one that a later
## build, or a person with a text editor, can.
var _refused_path: String = ""


func _ready() -> void:
	_load()


## The record for a mode. Takes the flag rather than reading `endless`, so the
## title screen can show both without having to lie about which mode is selected.
func best_for(for_endless: bool) -> int:
	return endless_high_score if for_endless else campaign_high_score


## Called once a run ends (win or lose). Only ever raises the record — a worse
## run than last time should not overwrite the number the player is proud of.
## Files against the mode that was actually played.
func record_score(seeds_earned: int) -> bool:
	if seeds_earned <= best_for(endless):
		return false
	if endless:
		endless_high_score = seeds_earned
	else:
		campaign_high_score = seeds_earned
	fresh_record = true
	_save()
	return true


## Has this player ever earned this milestone?
func has_milestone(id: String) -> bool:
	return earned_milestones.has(id)


## Files a finished run's milestones and hands back the ones that are NEW.
##
## The return value is the whole point: the card wants to say "you just did this
## for the first time", and by the time it asks, the flag is already set — so a
## caller that files first and reads after can only ever learn "you have this",
## which is true of a milestone earned three sessions ago. The newness exists for
## one instant, at the moment of the union, and this is that instant.
##
## Idempotent, deliberately. `Game._end_run` can be reached twice in a frame and
## both pause doors bank a score; a second call with the same ids adds nothing,
## returns nothing and — because nothing changed — does not write the file either.
func record_milestones(ids: Array) -> Array[String]:
	var fresh: Array[String] = []
	for id: Variant in ids:
		var text: String = String(id)
		if text.is_empty() or has_milestone(text):
			continue
		earned_milestones[text] = true
		fresh.append(text)
	if not fresh.is_empty():
		_save()
	return fresh


## Where `_save` assembles the next file before it replaces `save_path`.
func _tmp_path() -> String:
	return save_path + ".tmp"


## Where a refused file is quarantined, rather than being overwritten.
func _backup_path() -> String:
	return save_path + ".bak"


## A score field is a plain non-negative integer and nothing else.
##
## The `""` case is the whole issue: `get_line()` returns `""` past the end of a
## truncated file, `int("")` is 0 in GDScript, and 0 is a legal-looking high
## score. Every other malformed field at least looks wrong; this one looks like a
## player who never played.
static func _is_score(text: String) -> bool:
	return text.is_valid_int() and int(text) >= 0


## The milestone line, or `null` if it is not one.
##
## Shape: `m0` for the empty set, `m3:alpha,beta,gamma` otherwise. The count is not
## decoration — it is the only thing that can catch a line truncated at a comma,
## which is the shape a short write actually leaves. A cut that lands mid-id still
## parses (as an id this build does not know), and that is an accepted limit: the
## cost is one milestone the player re-earns, whereas refusing the file would cost
## the two scores they cannot.
##
## Ids are NOT checked against Milestones.TABLE. A save written by a later build
## carries ids this one has no rule for, and dropping them here would silently
## un-earn them the first time an older build touched the file.
##
## Returns Array[String] on success, `null` on anything else — a distinction
## `[]` cannot make, since the empty set is a legitimate reading.
static func _parse_milestones(text: String) -> Variant:
	if not text.begins_with(MILESTONE_PREFIX):
		return null
	var body: String = text.substr(MILESTONE_PREFIX.length())
	var colon: int = body.find(":")
	var count_text: String = body if colon < 0 else body.substr(0, colon)
	if not count_text.is_valid_int():
		return null
	var count: int = int(count_text)
	if count < 0:
		return null
	if (count == 0) != (colon < 0):
		# `m0:` and `m2` are both self-contradictory: a count with no list, or a
		# list with no count. Neither is a shape this writer produces.
		return null
	var ids: Array[String] = []
	if colon >= 0:
		for token: String in body.substr(colon + 1).split(","):
			if token.is_empty() or ids.has(token):
				return null
			for i: int in range(token.length()):
				if not MILESTONE_ID_CHARS.contains(token[i]):
					return null
			ids.append(token)
	if ids.size() != count:
		return null
	return ids


## The milestone set as one line, ids sorted so the bytes are a function of the
## set and not of the order it was assembled in.
func _milestone_line() -> String:
	var ids: Array = earned_milestones.keys()
	ids.sort()
	if ids.is_empty():
		return "%s0" % MILESTONE_PREFIX
	return "%s%d:%s" % [MILESTONE_PREFIX, ids.size(), ",".join(PackedStringArray(ids))]


func _parse_failed(reason: String) -> Dictionary:
	return {"ok": false, "campaign": 0, "endless": 0, "milestones": [], "version": 0, "reason": reason}


## Validates an entire save file and only then hands back its contents.
##
## Validate-then-commit rather than parse-defensively, deliberately: a parser
## that assigns campaign before discovering that the endless line is missing has
## already done the damage this function exists to prevent. There is no
## half-understood save worth half-adopting — the fields are two independent
## records, and taking one while dropping the other is indistinguishable from
## corruption on the next launch. So nothing here touches the live scores; the
## caller commits, or does not.
##
## Returns {ok: bool, campaign: int, endless: int, version: int, reason: String}.
func _parse_save(path: String) -> Dictionary:
	var f := FileAccess.open(path, FileAccess.READ)
	if f == null:
		return _parse_failed("cannot open it (%s)" % error_string(FileAccess.get_open_error()))
	var header: String = f.get_line().strip_edges()
	if header == "":
		return _parse_failed("it is empty")

	if not header.begins_with("v"):
		# Version 1: a bare integer on one line, and nothing else. No build ever
		# wrote a literal "v1" header, so the absence of the header IS the version.
		if not _is_score(header):
			return _parse_failed("its first line %s is neither a version nor a score" % [header])
		# That legacy number is migrated into the ENDLESS slot, and the choice is
		# not arbitrary: the title screen has always presented it as "Best endless
		# run", so that is the record the player believes they hold, and endless
		# totals dwarf campaign ones (eight waves against an unbounded run) — so a
		# legacy value that did come from a campaign is merely a hard endless
		# record, whereas the reverse migration would leave an unbeatable number
		# sitting on the eight-wave mode.
		# No build that wrote this shape ever had a milestone, so the empty set here
		# is a reading and not a fallback.
		return {"ok": true, "campaign": 0, "endless": int(header), "milestones": [],
			"version": 1, "reason": "v1"}

	var version_text: String = header.substr(1)
	if not version_text.is_valid_int():
		return _parse_failed("its version header %s is not a number" % [header])
	var version: int = int(version_text)
	if version > SAVE_VERSION:
		# The real point of reading the version at all. A later build may write
		# four lines, or the same three in another order, or the same three
		# meaning something else. Parsing it "as if it were current" is how a
		# newer build's endless record lands in the campaign slot silently. The
		# safe response to a file from the future is to decline to read it — and,
		# just as importantly, to decline to write over it, because that file is
		# not damaged, it is simply not ours. See `_load`.
		return _parse_failed("it is version %d and this build reads at most %d" % [version, SAVE_VERSION])
	if version < 2:
		return _parse_failed("version %d never had a %s header" % [version, header])

	# Version 2 and up: campaign, then endless, one per line.
	var campaign_text: String = f.get_line().strip_edges()
	var endless_text: String = f.get_line().strip_edges()
	if not _is_score(campaign_text):
		return _parse_failed("its campaign score %s is not a number" % [campaign_text])
	if not _is_score(endless_text):
		return _parse_failed("its endless score %s is not a number" % [endless_text])

	# Version 3 adds the milestone line. A version-2 file simply has none, which is
	# the migration: the flags start empty and `_load` rewrites the file in the new
	# shape once, exactly as it does for a version-1 file.
	var milestones: Array = []
	if version >= 3:
		var parsed_ids: Variant = _parse_milestones(f.get_line().strip_edges())
		if parsed_ids == null:
			return _parse_failed("its milestone line is not a milestone line")
		milestones = parsed_ids as Array

	return {
		"ok": true,
		"campaign": int(campaign_text),
		"endless": int(endless_text),
		"milestones": milestones,
		"version": version,
		"reason": "v%d" % version,
	}


## Reads the save, or refuses to.
##
## Nothing is written on the refusal path — not the fallback, not a "repaired"
## file, nothing. Overwriting the file we just failed to read is the one action
## that turns a recoverable situation into a permanent one, and it is precisely
## what the old version-1 branch did on every launch.
func _load() -> void:
	var path: String = save_path
	var recovered: bool = false
	# Whatever a previous load refused, this one supersedes: a quarantine that is
	# still pending against a file nobody is going to read again is just a stale
	# rename waiting to fire at the wrong moment.
	_refused_path = ""
	if not FileAccess.file_exists(path):
		# An interrupted `_save` can leave a complete temp file with no save
		# beside it. Adopting it is the entire reason `_save` writes it
		# separately; without this, the safety net catches nothing.
		if not FileAccess.file_exists(_tmp_path()):
			load_status = "absent"
			return
		path = _tmp_path()
		recovered = true

	var parsed: Dictionary = _parse_save(path)
	if not bool(parsed["ok"]):
		load_status = "refused"
		_refused_path = path
		push_warning("RunConfig: refusing %s because %s. High scores left as they are (campaign %d, endless %d)."
			% [path, str(parsed["reason"]), campaign_high_score, endless_high_score])
		return

	campaign_high_score = int(parsed["campaign"])
	endless_high_score = int(parsed["endless"])
	# Replaced, not merged. A load is "this is what is on disk", and a union with
	# whatever the process happened to be holding would make a save reloaded twice
	# read differently from one loaded once.
	earned_milestones = {}
	for id: String in (parsed["milestones"] as Array):
		earned_milestones[id] = true
	if recovered:
		load_status = "recovered"
		_save()
	elif int(parsed["version"]) < SAVE_VERSION:
		load_status = "migrated"
		# Rewrite immediately in the new shape, so the ambiguity is resolved once
		# rather than being re-guessed on every launch. Unlike the refusal path,
		# this write follows a parse that fully succeeded.
		_save()
	else:
		load_status = "loaded"


## Assembles the file at a temp path and only then replaces `save_path`.
##
## Judged warranted, not ceremony, for a three-line file. `FileAccess.WRITE`
## truncates its target the instant it opens, so the previous shape destroyed the
## only copy of an unregenerable number *before* writing a byte of the
## replacement — and it did that on every new record. A full or read-only user://
## therefore turned "could not save" into "the previous save is now a zero-length
## file", which is the exact truncation the reader above now has to refuse. Fixing
## only the reader would leave that: the live session keeps its number, and the
## next launch starts at zero anyway. The write side is the half that actually
## keeps the data.
##
## Honest caveat: Godot's `DirAccess.rename_absolute` removes an existing
## destination before renaming on Windows, so this is not a true atomic swap
## there. It shrinks the window from "the whole write" to "one rename", and the
## finished temp file is still on disk if we lose even that — which is why `_load`
## adopts the temp when the save has gone missing.
func _save() -> void:
	if _refused_path != "":
		# Move the file `_load` could not read aside rather than over it. First
		# refusal wins: that file is the one closest to the data the player set,
		# and a second corruption should not be allowed to bury it.
		if FileAccess.file_exists(_refused_path) and not FileAccess.file_exists(_backup_path()):
			DirAccess.rename_absolute(_refused_path, _backup_path())
		_refused_path = ""

	var tmp: String = _tmp_path()
	var f := FileAccess.open(tmp, FileAccess.WRITE)
	if f == null:
		push_warning("RunConfig: cannot write %s (%s). The record stands in memory only, and the previous save is untouched."
			% [tmp, error_string(FileAccess.get_open_error())])
		return
	f.store_line("v%d" % SAVE_VERSION)
	f.store_line(str(campaign_high_score))
	f.store_line(str(endless_high_score))
	f.store_line(_milestone_line())
	f.flush()
	var write_error: int = f.get_error()
	f.close()
	if write_error != OK:
		# A short write is exactly the truncation this whole issue is about. Here
		# it lands in the temp file, where it can be thrown away instead of read.
		push_warning("RunConfig: %s while writing %s. Keeping the previous save."
			% [error_string(write_error), tmp])
		DirAccess.remove_absolute(tmp)
		return
	var readback: Dictionary = _parse_save(tmp)
	if not bool(readback["ok"]):
		# Read back through the same validator the loader uses, so "whatever is at
		# save_path parses" is true by construction rather than by argument — and
		# so a future writer that its own reader cannot read fails here, loudly,
		# instead of at some player's next launch.
		push_warning("RunConfig: %s does not read back (%s). Keeping the previous save."
			% [tmp, str(readback["reason"])])
		DirAccess.remove_absolute(tmp)
		return
	var rename_error: int = DirAccess.rename_absolute(tmp, save_path)
	if rename_error != OK:
		push_warning("RunConfig: %s replacing %s. The finished save is at %s and _load will adopt it."
			% [error_string(rename_error), save_path, tmp])
