#!/usr/bin/env python3
"""Generate a GDScript boolean-input classifier and its matching unit test
block from one JSON spec, so the branch table and the assertions that check
it are derived from the same source and cannot drift apart (the
derive-the-list pattern applied to code generation instead of to a runtime
list).

A spec describes an ordered list of cases; each case is a partial
assignment of the function's boolean params ("when") mapped to the GDScript
expression to return ("value"). Cases are tried in order, first match wins
-- exactly like the hand-written if-chains this project already writes for
functions such as Hud.plant_button_tint and Hud.threat_color. A case with an
empty "when" is the unconditional default and must be last.

Usage:
    python tools/gen_bool_classifier.py SPEC.json --print-func
    python tools/gen_bool_classifier.py SPEC.json --print-test

The GDScript body and the test body are both derived from `cases` --
edit the spec, regenerate both, nothing is hand-typed in two places.
"""

from __future__ import annotations

import argparse
import itertools
import json
import sys
from pathlib import Path
from typing import Any


def _cond_expr(param_names: list[str], when: dict[str, bool]) -> str:
    if not when:
        return "true"
    parts = []
    for name in param_names:
        if name not in when:
            continue
        parts.append(name if when[name] else f"not {name}")
    return " and ".join(parts)


def generate_function(spec: dict[str, Any]) -> str:
    name = spec["function"]
    params = spec["params"]  # list of [name, type]
    return_type = spec.get("return_type", "Color")
    param_names = [p[0] for p in params]
    sig = ", ".join(f"{p[0]}: {p[1]}" for p in params)
    lines = [f"static func {name}({sig}) -> {return_type}:"]
    cases = spec["cases"]
    for i, case in enumerate(cases):
        when = case.get("when", {})
        value = case["value"]
        is_last = i == len(cases) - 1
        if not when and is_last:
            lines.append(f"\treturn {value}")
            continue
        cond = _cond_expr(param_names, when)
        lines.append(f"\tif {cond}:")
        lines.append(f"\t\treturn {value}")
    return "\n".join(lines) + "\n"


def _matches(when: dict[str, bool], witness: dict[str, bool]) -> bool:
    return all(witness[k] == v for k, v in when.items())


def _witness_for(param_names: list[str], cases: list[dict[str, Any]], index: int) -> dict[str, bool]:
    """The smallest boolean assignment that reaches `cases[index]` when the
    cases are evaluated in order as a real if-chain -- i.e. it satisfies
    cases[index]'s own `when` and does NOT satisfy any earlier case's `when`.
    Raises if the spec has no such assignment (an earlier case fully shadows
    this one, which means the spec itself is wrong, not just the codegen)."""
    when = cases[index].get("when", {})
    free = [p for p in param_names if p not in when]
    for combo in itertools.product([False, True], repeat=len(free)):
        witness = dict(when)
        witness.update(dict(zip(free, combo)))
        if any(_matches(cases[j].get("when", {}), witness) for j in range(index)):
            continue
        return witness
    raise ValueError(
        f"case {index} ({when!r}) is unreachable -- every assignment satisfying "
        "it is already claimed by an earlier case"
    )


def generate_test(spec: dict[str, Any]) -> str:
    name = spec["function"]
    owner = spec.get("class", "")
    params = spec["params"]
    param_names = [p[0] for p in params]
    cases = spec["cases"]
    call_prefix = f"{owner}.{name}" if owner else name
    lines = [
        f"# Generated by tools/gen_bool_classifier.py from a spec -- one assertion",
        f"# per case in the spec, in spec order, so a case added to the branch",
        f"# table and forgotten in the test (or the reverse) fails this block.",
    ]
    for i, case in enumerate(cases):
        witness = _witness_for(param_names, cases, i)
        args = ", ".join(str(witness[p]).lower() for p in param_names)
        desc = case.get("desc", json.dumps(case.get("when", {})))
        raw_value = case["value"]
        # A bare constant name (no "." already in it, e.g. not `Color.WHITE`)
        # is a member of `owner` -- the generated function body is a method
        # ON that class so it reads unqualified there, but the test lives in
        # a different class and needs the same constant written qualified.
        value = f"{owner}.{raw_value}" if owner and "." not in raw_value else raw_value
        lines.append(
            f'err = _T.assert_eq({call_prefix}({args}), {value}, '
            f'"{name}: {desc}")'
        )
        lines.append("if err != \"\": return err")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("spec", type=Path)
    ap.add_argument("--print-func", action="store_true")
    ap.add_argument("--print-test", action="store_true")
    args = ap.parse_args()

    spec = json.loads(args.spec.read_text())

    if not args.print_func and not args.print_test:
        args.print_func = args.print_test = True

    if args.print_func:
        print(generate_function(spec))
    if args.print_test:
        print(generate_test(spec))
    return 0


if __name__ == "__main__":
    sys.exit(main())
